# Generated by Django 4.2.12 on 2026-01-29 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_approve_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_manage_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_view_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='department_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('hr_manager', 'HR Manager'), ('admin', 'Administrator')], default='employee', max_length=20),
        ),
        migrations.CreateModel(
            name='ManagerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('hr_manager', 'HR Manager'), ('admin', 'Administrator')], max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_manager_requests', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_requests', to='accounts.employee')),
            ],
            options={
                'verbose_name': 'Manager Request',
                'verbose_name_plural': 'Manager Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
