# Generated by Django 4.2.12 on 2026-01-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_can_approve_leave_employee_can_manage_team_and_more'),
    ]

    operations = [
        # First, make the fields nullable to allow existing records
        migrations.AlterField(
            model_name='employee',
            name='can_approve_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='can_manage_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='can_view_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('hr_manager', 'HR Manager'), ('admin', 'Administrator')], default='employee', max_length=20),
        ),
    ]
