# Generated by Django 4.2.12 on 2026-01-29 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20260129_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='team_description',
            field=models.TextField(blank=True, help_text='Description of the team', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='team_leader',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'team_leader'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='team_name',
            field=models.CharField(blank=True, help_text='Team name for team leaders', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('team_leader', 'Team Leader'), ('manager', 'Manager'), ('hr_manager', 'HR Manager'), ('admin', 'Administrator')], default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='managerrequest',
            name='requested_role',
            field=models.CharField(choices=[('employee', 'Employee'), ('team_leader', 'Team Leader'), ('manager', 'Manager'), ('hr_manager', 'HR Manager'), ('admin', 'Administrator')], max_length=20),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(choices=[('sales', 'Sales'), ('marketing', 'Marketing'), ('engineering', 'Engineering'), ('hr', 'Human Resources'), ('finance', 'Finance'), ('operations', 'Operations'), ('support', 'Customer Support'), ('admin', 'Administration')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('team_leader', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_team', to='accounts.employee')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
    ]
