# Generated by Django 4.2.12 on 2026-01-30 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employee_team_description_employee_team_leader_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='reporting_to',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='team_description',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='team_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Manager for Team Leaders', limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_leaders', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('team_leader', 'Team Leader'), ('manager', 'Manager'), ('superadmin', 'SuperAdmin')], default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='team_leader',
            field=models.ForeignKey(blank=True, help_text='Team Leader for Employees', limit_choices_to={'role': 'team_leader'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='managerrequest',
            name='requested_role',
            field=models.CharField(choices=[('employee', 'Employee'), ('team_leader', 'Team Leader'), ('manager', 'Manager'), ('superadmin', 'SuperAdmin')], max_length=20),
        ),
    ]
