# Generated by Django 4.2.12 on 2026-01-30 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_employee_reporting_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='can_approve_leave',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='can_manage_team',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='can_view_reports',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department_head',
        ),
    ]
