# Generated by Django 4.2.12 on 2026-02-03 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_old_permission_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='reports_to',
            field=models.ForeignKey(blank=True, help_text='Reports to (Manager/Team Leader)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Manager for Team Leaders', limit_choices_to={'role__in': ['manager', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_leaders', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('team_leader', 'Team Leader'), ('manager', 'Manager'), ('admin', 'Admin'), ('superadmin', 'SuperAdmin')], default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='managerrequest',
            name='requested_role',
            field=models.CharField(choices=[('employee', 'Employee'), ('team_leader', 'Team Leader'), ('manager', 'Manager'), ('admin', 'Admin'), ('superadmin', 'SuperAdmin')], max_length=20),
        ),
    ]
