# Generated by Django 4.2.12 on 2026-02-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_excelbatch_excelbatchrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelbatchrow',
            name='row_data',
            field=models.TextField(),
        ),
    ]
