# Generated by Django 4.2.12 on 2026-02-07 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_create_uploaded_lead_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='additional_data',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='company',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='position',
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_leads', to='accounts.employee'),
        ),
        migrations.DeleteModel(
            name='UploadedLead',
        ),
    ]
