# Generated by Django 4.2.12 on 2026-02-09 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_rename_additional_data_lead_data_remove_lead_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_count', models.PositiveIntegerField(default=0, help_text='Number of files processed')),
                ('login_count', models.PositiveIntegerField(default=0, help_text='Number of logins recorded')),
                ('total_count', models.PositiveIntegerField(default=0, help_text='Total count for tracking')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date for these statistics')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(help_text='Manager responsible for these statistics', limit_choices_to={'role__in': ['manager', 'admin', 'superadmin']}, on_delete=django.db.models.deletion.CASCADE, related_name='manager_login_stats', to='accounts.employee')),
                ('team_leader', models.ForeignKey(blank=True, help_text='Team leader (optional - for manager-level stats)', limit_choices_to={'role': 'team_leader'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_leader_login_stats', to='accounts.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_login_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Statistics',
                'verbose_name_plural': 'Login Statistics',
                'ordering': ['-date', 'manager', 'team_leader'],
                'unique_together': {('manager', 'team_leader', 'date')},
            },
        ),
    ]
