# Generated by Django 5.2.5 on 2026-02-10 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_loginstatistics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(help_text='Time when user logged in (IST)')),
                ('logout_time', models.DateTimeField(blank=True, help_text='Time when user logged out (IST)', null=True)),
                ('session_duration', models.DurationField(blank=True, help_text='Total duration of the session', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which user logged in', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information', null=True)),
                ('is_active_session', models.BooleanField(default=True, help_text='Whether this session is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'ordering': ['-login_time'],
            },
        ),
    ]
