# Generated by Django 5.2.5 on 2026-02-10 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_useractivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('status_changed', 'Status Changed'), ('note_added', 'Note Added'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('deleted', 'Deleted')], help_text='Type of action performed', max_length=20)),
                ('old_value', models.TextField(blank=True, help_text='Previous value before update', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value after update', null=True)),
                ('description', models.TextField(help_text='Detailed description of the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which action was performed', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='accounts.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Activity Log',
                'verbose_name_plural': 'Lead Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', '-created_at'], name='accounts_le_lead_id_a3ab7b_idx'), models.Index(fields=['user', '-created_at'], name='accounts_le_user_id_631a5a_idx'), models.Index(fields=['action_type', '-created_at'], name='accounts_le_action__106f3f_idx')],
            },
        ),
    ]
