# Generated by Django 5.2.5 on 2026-02-10 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_leadactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the timesheet')),
                ('total_hours', models.DecimalField(decimal_places=2, help_text='Total hours worked for the day', max_digits=5)),
                ('notes', models.TextField(blank=True, help_text='Daily notes about work performed')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Admin review notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='accounts.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_timesheets', to='accounts.employee')),
            ],
            options={
                'verbose_name': 'Timesheet',
                'verbose_name_plural': 'Timesheets',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(help_text='Start time for this work entry')),
                ('end_time', models.TimeField(help_text='End time for this work entry')),
                ('hours_worked', models.DecimalField(decimal_places=2, help_text='Hours worked in this entry', max_digits=5)),
                ('activity_type', models.CharField(choices=[('lead_work', 'Lead Work'), ('calling', 'Calling'), ('emailing', 'Emailing'), ('meeting', 'Meeting'), ('training', 'Training'), ('admin', 'Admin Work'), ('other', 'Other')], default='lead_work', max_length=20)),
                ('description', models.TextField(help_text='Description of work performed during this time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leads_worked', models.ManyToManyField(blank=True, help_text='Leads worked on during this time', related_name='timesheet_entries', to='accounts.lead')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounts.timesheet')),
            ],
            options={
                'verbose_name': 'Timesheet Entry',
                'verbose_name_plural': 'Timesheet Entries',
                'ordering': ['start_time'],
            },
        ),
    ]
