# Generated by Django 5.2.5 on 2026-02-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_timesheet_timesheetentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total hours worked for the day', max_digits=5),
        ),
    ]
