# Generated by Django 5.2.5 on 2026-02-11 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_timesheet_total_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetentry',
            name='timesheet',
        ),
        migrations.RemoveField(
            model_name='timesheetentry',
            name='leads_worked',
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of attendance')),
                ('check_in', models.DateTimeField(blank=True, help_text='Time when employee started work', null=True)),
                ('check_out', models.DateTimeField(blank=True, help_text='Time when employee ended work', null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('leave', 'Leave')], default='present', max_length=20)),
                ('total_work_hours', models.DecimalField(decimal_places=2, default=0, help_text='Total work hours including overtime', max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, help_text='Overtime hours worked', max_digits=5)),
                ('late_by_minutes', models.IntegerField(default=0, help_text='Minutes late to work')),
                ('early_departure_minutes', models.IntegerField(default=0, help_text='Minutes left early from work')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.employee')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_type', models.CharField(choices=[('tea_morning', 'Morning Tea Break'), ('lunch', 'Lunch Break'), ('tea_evening', 'Evening Tea Break'), ('other', 'Other Break')], max_length=20)),
                ('start_time', models.DateTimeField(help_text='Break start time')),
                ('end_time', models.DateTimeField(blank=True, help_text='Break end time', null=True)),
                ('scheduled_start', models.TimeField(help_text='Scheduled break start time')),
                ('scheduled_end', models.TimeField(help_text='Scheduled break end time')),
                ('duration_minutes', models.IntegerField(default=0, help_text='Actual break duration in minutes')),
                ('is_violation', models.BooleanField(default=False, help_text='Whether break timing was violated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='accounts.attendance')),
            ],
            options={
                'verbose_name': 'Attendance Break',
                'verbose_name_plural': 'Attendance Breaks',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('late_check_in', 'Late Check-in'), ('early_check_out', 'Early Check-out'), ('break_violation', 'Break Time Violation'), ('absent', 'Absent Without Leave'), ('short_hours', 'Insufficient Work Hours')], max_length=20)),
                ('violation_time', models.DateTimeField(help_text='Time when violation occurred')),
                ('description', models.TextField(help_text='Description of the violation')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='accounts.attendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_violations', to='accounts.employee')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_violations', to='accounts.employee')),
            ],
            options={
                'verbose_name': 'Attendance Violation',
                'verbose_name_plural': 'Attendance Violations',
                'ordering': ['-violation_time'],
            },
        ),
        migrations.DeleteModel(
            name='Timesheet',
        ),
        migrations.DeleteModel(
            name='TimesheetEntry',
        ),
    ]
