# Generated by Django 4.2.12 on 2026-02-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_timesheetentry_timesheet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancebreak',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='attendanceviolation',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='attendanceviolation',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='attendanceviolation',
            name='resolved_by',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='AttendanceBreak',
        ),
        migrations.DeleteModel(
            name='AttendanceViolation',
        ),
    ]
