# Generated by Django 5.2.5 on 2026-02-11 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_attendancebreak_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Attendance date')),
                ('start_time', models.DateTimeField(blank=True, help_text='Actual start time', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='Actual end time', null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('early_leave', 'Early Leave'), ('half_day', 'Half Day')], default='present', max_length=20)),
                ('expected_start_time', models.TimeField(default='09:30:00', help_text='Expected start time (9:30 AM)')),
                ('expected_end_time', models.TimeField(default='18:30:00', help_text='Expected end time (6:30 PM)')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, help_text='Total working hours', max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, help_text='Overtime hours after 6:30 PM', max_digits=5)),
                ('break_hours', models.DecimalField(decimal_places=2, default=0, help_text='Total break time', max_digits=5)),
                ('is_active', models.BooleanField(default=False, help_text='Whether employee is currently working')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.employee')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_type', models.CharField(choices=[('tea_morning', 'Morning Tea Break (11:00-11:15 AM)'), ('lunch', 'Lunch Break (1:00-1:30 PM)'), ('tea_afternoon', 'Afternoon Tea Break (4:00-4:15 PM)'), ('other', 'Other Break')], default='other', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, help_text='Break start time', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='Break end time', null=True)),
                ('duration_hours', models.DecimalField(decimal_places=2, default=0, help_text='Break duration in hours', max_digits=4)),
                ('is_auto_break', models.BooleanField(default=False, help_text='Whether this is an automatic scheduled break')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='accounts.attendance')),
            ],
            options={
                'verbose_name': 'Break',
                'verbose_name_plural': 'Breaks',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('late_arrival', 'Late Arrival'), ('early_departure', 'Early Departure'), ('missed_break', 'Missed Scheduled Break'), ('extended_break', 'Extended Break'), ('no_checkout', 'No Checkout')], max_length=20)),
                ('description', models.TextField(help_text='Description of the violation')),
                ('violation_time', models.DateTimeField(help_text='When the violation occurred')),
                ('expected_time', models.DateTimeField(blank=True, help_text='What the expected time should have been', null=True)),
                ('time_difference_minutes', models.IntegerField(default=0, help_text='Time difference in minutes (positive = late/over, negative = early/under)')),
                ('resolved', models.BooleanField(default=False, help_text='Whether the violation has been resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='accounts.attendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='accounts.employee')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_violations', to='accounts.employee')),
            ],
            options={
                'verbose_name': 'Violation',
                'verbose_name_plural': 'Violations',
                'ordering': ['-violation_time'],
            },
        ),
    ]
