# Generated by Django 5.2.5 on 2026-02-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_leave_leaveapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('not_eligible', 'Not Eligible'), ('converted', 'Converted'), ('follow_up', 'Follow Up Required'), ('file_login', 'File Login'), ('amount_disbursed', 'Amount Disbursed')], default='new', max_length=20),
        ),
    ]
