# Generated by Django 5.2.5 on 2026-02-12 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_lead_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('phone_type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('official', 'Official')], default='primary', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Employee Phone Number',
                'verbose_name_plural': 'Employee Phone Numbers',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='leadactivitylog',
            name='accounts_le_lead_id_a3ab7b_idx',
        ),
        migrations.RemoveIndex(
            model_name='leadactivitylog',
            name='accounts_le_user_id_631a5a_idx',
        ),
        migrations.RemoveIndex(
            model_name='leadactivitylog',
            name='accounts_le_action__106f3f_idx',
        ),
        migrations.RemoveField(
            model_name='leadactivitylog',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='employeephone',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeephone',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='accounts.employee'),
        ),
    ]
