# Generated by Django 5.2.5 on 2026-02-13 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_employeephone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadForward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Message from admin to employee')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('forwarded_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('forwarded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_forwards', to='accounts.employee')),
                ('forwarded_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_forwards', to='accounts.employee')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwards', to='accounts.lead')),
            ],
            options={
                'verbose_name': 'Lead Forward',
                'verbose_name_plural': 'Lead Forwards',
                'ordering': ['-forwarded_at'],
                'unique_together': {('lead', 'forwarded_to')},
            },
        ),
    ]
