# Generated by Django 4.2.12 on 2026-02-13 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_csvuploadbatch_uploaded_by_and_more'),
        ('accounts', '0024_leadforward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadforward',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_forwards', to='crm.lead'),
        ),
    ]
