# Generated by Django 5.2.5 on 2026-02-14 11:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_leadforward_lead'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leadforward',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='leadforward',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When the record was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadforward',
            name='employee_notes',
            field=models.TextField(blank=True, default='', help_text='Notes added by employee', null=True),
        ),
        migrations.AddField(
            model_name='leadforward',
            name='lead_email',
            field=models.EmailField(blank=True, help_text='Email of the lead', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='leadforward',
            name='lead_name',
            field=models.CharField(default='', help_text='Name of the lead', max_length=255),
        ),
        migrations.AddField(
            model_name='leadforward',
            name='lead_phone',
            field=models.CharField(blank=True, default='', help_text='Phone number of the lead', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leadforward',
            name='lead_source',
            field=models.CharField(default='', help_text='Source of the lead (e.g., Excel sheet name)', max_length=100),
        ),
        migrations.AddField(
            model_name='leadforward',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Additional notes from team leader', null=True),
        ),
        migrations.AddField(
            model_name='leadforward',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the record was last updated'),
        ),
        migrations.AlterField(
            model_name='break',
            name='break_type',
            field=models.CharField(choices=[('tea_morning', 'Morning Tea Break'), ('lunch', 'Lunch Break'), ('tea_afternoon', 'Afternoon Tea Break'), ('other', 'Other Break')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadforward',
            name='accepted_at',
            field=models.DateTimeField(blank=True, default=None, help_text='When the lead was accepted by employee', null=True),
        ),
        migrations.AlterField(
            model_name='leadforward',
            name='completed_at',
            field=models.DateTimeField(blank=True, default=None, help_text='When the lead was completed', null=True),
        ),
        migrations.AlterField(
            model_name='leadforward',
            name='forwarded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the lead was forwarded'),
        ),
        migrations.AlterField(
            model_name='leadforward',
            name='forwarded_by',
            field=models.ForeignKey(help_text='Team leader who forwarded the lead', on_delete=django.db.models.deletion.CASCADE, related_name='forwarded_leads', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='leadforward',
            name='forwarded_to',
            field=models.ForeignKey(help_text='Employee who received the forwarded lead', on_delete=django.db.models.deletion.CASCADE, related_name='received_leads', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='leadforward',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('forwarded', 'Forwarded'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', help_text='Current status of the forwarded lead', max_length=20),
        ),
        migrations.AddIndex(
            model_name='leadforward',
            index=models.Index(fields=['forwarded_by', 'status'], name='accounts_le_forward_22601f_idx'),
        ),
        migrations.AddIndex(
            model_name='leadforward',
            index=models.Index(fields=['forwarded_to', 'status'], name='accounts_le_forward_8783ba_idx'),
        ),
        migrations.AddIndex(
            model_name='leadforward',
            index=models.Index(fields=['forwarded_at'], name='accounts_le_forward_db6b3b_idx'),
        ),
        migrations.RemoveField(
            model_name='leadforward',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='leadforward',
            name='message',
        ),
        migrations.RemoveField(
            model_name='leadforward',
            name='priority',
        ),
    ]
