# Generated by Django 5.2.5 on 2026-02-16 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_leadforward_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadforward',
            name='lead_id',
            field=models.CharField(default='', help_text='ID of the lead being forwarded', max_length=100),
        ),
        migrations.AlterField(
            model_name='leadforward',
            name='forwarded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_forwards', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='leadforward',
            name='forwarded_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_forwards', to='accounts.employee'),
        ),
    ]
