# Generated by Django 5.2.5 on 2026-02-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_leadforward_lead_id_alter_leadforward_forwarded_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('team_leader', 'Team Leader'), ('manager', 'Manager'), ('hr', 'HR'), ('admin', 'Admin'), ('superadmin', 'SuperAdmin')], default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='managerrequest',
            name='requested_role',
            field=models.CharField(choices=[('employee', 'Employee'), ('team_leader', 'Team Leader'), ('manager', 'Manager'), ('hr', 'HR'), ('admin', 'Admin'), ('superadmin', 'SuperAdmin')], max_length=20),
        ),
    ]
