# Generated by Django 4.2.12 on 2026-02-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_add_hr_role'),
        ('accounts', '0028_alter_employee_role_and_more'),
    ]

    operations = [
    ]
