# Generated by Django 4.2.12 on 2026-02-16 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0029_merge_20260216_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('resume', 'Resume'), ('contract', 'Employment Contract'), ('id_proof', 'ID Proof'), ('address_proof', 'Address Proof'), ('experience_letter', 'Experience Letter'), ('salary_slip', 'Salary Slip'), ('aadhar_card', 'Aadhar Card'), ('pan_card', 'PAN Card'), ('highest_education', 'Highest Education Certificate'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=200, verbose_name='Account Holder Name')),
                ('account_number', models.CharField(max_length=50, verbose_name='Account Number')),
                ('bank_name', models.CharField(max_length=200, verbose_name='Bank Name')),
                ('branch_name', models.CharField(max_length=200, verbose_name='Branch Name')),
                ('ifsc_code', models.CharField(max_length=20, verbose_name='IFSC Code')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='accounts.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Details',
                'verbose_name_plural': 'Bank Details',
            },
        ),
    ]
