# Generated by Django 4.2.12 on 2026-02-16 11:05

import apps.accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0030_alter_document_document_type_bankdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='account_holder_name',
            field=models.CharField(blank=True, help_text='Account Holder Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='account_number',
            field=models.CharField(blank=True, help_text='Bank Account Number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Name of the Bank', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='branch_name',
            field=models.CharField(blank=True, help_text='Branch Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ifsc_code',
            field=models.CharField(blank=True, help_text='IFSC Code', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('aadhar_card', 'Aadhar Card'), ('pan_card', 'PAN Card'), ('highest_education', 'Highest Education Certificate'), ('bank_details', 'Bank Details'), ('resume', 'Resume'), ('contract', 'Employment Contract'), ('id_proof', 'ID Proof'), ('address_proof', 'Address Proof'), ('experience_letter', 'Experience Letter'), ('salary_slip', 'Salary Slip'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='employee_documents/%Y/%m/%d/', validators=[apps.accounts.models.validate_file_size]),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('employee', 'document_type')},
        ),
        migrations.DeleteModel(
            name='BankDetails',
        ),
    ]
