# Generated by Django 5.2.5 on 2026-02-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_document_account_holder_name_document_account_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('resume', 'Resume'), ('contract', 'Employment Contract'), ('id_proof', 'ID Proof'), ('address_proof', 'Address Proof'), ('experience_letter', 'Experience Letter'), ('salary_slip', 'Salary Slip'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='employee_documents/%Y/%m/'),
        ),
        migrations.RemoveField(
            model_name='document',
            name='account_holder_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='document',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='document',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='verified_by',
        ),
    ]
