# Generated by Django 4.2.12 on 2026-02-17 07:35

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_document_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='branch_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('resume', 'Resume'), ('contract', 'Employment Contract'), ('id_proof', 'ID Proof'), ('address_proof', 'Address Proof'), ('experience_letter', 'Experience Letter'), ('salary_slip', 'Salary Slip'), ('bank_details', 'Bank Details/Passbook'), ('pan_card', 'PAN Card'), ('aadhaar_card', 'Aadhaar Card'), ('passport', 'Passport'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=apps.accounts.models.get_upload_path),
        ),
    ]
