# Generated by Django 4.2.12 on 2026-02-17 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_document_account_number_document_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='corrected_at',
            field=models.DateTimeField(blank=True, help_text='When the attendance was corrected', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='corrected_by',
            field=models.ForeignKey(blank=True, help_text='HR/Admin who corrected this attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_attendances', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='correction_notes',
            field=models.TextField(blank=True, help_text='Notes for manual correction', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='correction_status',
            field=models.CharField(choices=[('auto_calculated', 'Auto Calculated'), ('manually_corrected', 'Manually Corrected')], default='auto_calculated', help_text='Whether status is auto-calculated or manually corrected', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='final_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('early_leave', 'Early Leave'), ('half_day', 'Half Day'), ('full_day_present', 'Full Day Present')], default='present', help_text='Final status after manual correction', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('early_leave', 'Early Leave'), ('half_day', 'Half Day'), ('full_day_present', 'Full Day Present')], default='present', max_length=20),
        ),
    ]
