# Generated by Django 5.2.5 on 2026-02-18 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_ticket_ticketcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='current_handler',
            field=models.ForeignKey(blank=True, help_text='Employee currently working on this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_leads', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Lead is locked for editing by current handler'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lock_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the lock expires', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='When the lead was locked', null=True),
        ),
        migrations.CreateModel(
            name='LeadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='Unique batch identifier', max_length=50, unique=True)),
                ('data_source', models.CharField(help_text='Source file name or origin', max_length=100)),
                ('total_leads', models.PositiveIntegerField(default=0, help_text='Total number of leads in this batch')),
                ('status', models.CharField(choices=[('pending', 'Pending Assignment'), ('assigned', 'Assigned to TL'), ('distributed', 'Distributed to Employees'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('leads_completed', models.PositiveIntegerField(default=0, help_text='Number of leads completed')),
                ('leads_in_progress', models.PositiveIntegerField(default=0, help_text='Number of leads currently being worked on')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Admin who assigned this batch', limit_choices_to={'role__in': ['admin', 'superadmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to='accounts.employee')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Team Leader or Manager assigned to this batch', limit_choices_to={'role__in': ['team_leader', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_batches', to='accounts.employee')),
            ],
            options={
                'verbose_name': 'Lead Batch',
                'verbose_name_plural': 'Lead Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch this lead belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='accounts.leadbatch'),
        ),
    ]
