# Generated by Django 4.2.12 on 2026-02-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_lead_current_handler_lead_is_locked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='batch',
        ),
        migrations.AddField(
            model_name='leadbatch',
            name='leads',
            field=models.ManyToManyField(blank=True, help_text='Leads in this batch', related_name='batch_leads', to='accounts.lead'),
        ),
    ]
