# Generated by Django 4.2.12 on 2026-02-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_remove_lead_batch_leadbatch_leads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadbatch',
            name='leads',
            field=models.ManyToManyField(blank=True, help_text='Leads in this batch', related_name='batch_leads_collection', to='accounts.lead'),
        ),
    ]
