# Generated by Django 5.2.5 on 2026-02-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_leadbatch_leads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='current_handler',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lock_expires_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='locked_at',
        ),
        migrations.DeleteModel(
            name='LeadBatch',
        ),
    ]
