# Generated by Django 4.2.12 on 2026-02-20 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0040_remove_lead_current_handler_remove_lead_is_locked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='reports_to',
            field=models.ForeignKey(blank=True, help_text='Reports to (Manager/Team Leader)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='accounts.employee'),
        ),
        migrations.CreateModel(
            name='MISReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aro', models.CharField(blank=True, max_length=100, null=True)),
                ('login_date', models.DateField()),
                ('app_id', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=20)),
                ('applicant_type', models.CharField(choices=[('salaried', 'Salaried'), ('self_employed', 'Self Employed'), ('business', 'Business'), ('pensioner', 'Pensioner')], max_length=20)),
                ('dob', models.DateField()),
                ('pan_no', models.CharField(max_length=10)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('company_name', models.CharField(max_length=200)),
                ('login_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('disbursed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product', models.CharField(choices=[('personal_loan', 'Personal Loan'), ('business_loan', 'Business Loan'), ('home_loan', 'Home Loan'), ('car_loan', 'Car Loan'), ('education_loan', 'Education Loan')], max_length=50)),
                ('tanure', models.IntegerField(help_text='Loan tenure in months')),
                ('bank', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('current_status', models.CharField(blank=True, max_length=100, null=True)),
                ('banker_name', models.CharField(blank=True, max_length=100, null=True)),
                ('banker_no', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mis_reports', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'employee__role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_mis_reports', to=settings.AUTH_USER_MODEL)),
                ('team_leader', models.ForeignKey(blank=True, limit_choices_to={'employee__role': 'team_leader'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mis_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MIS Report',
                'verbose_name_plural': 'MIS Reports',
                'ordering': ['-login_date'],
            },
        ),
    ]
