# Generated by Django 4.2.12 on 2026-02-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_employee_reports_to_misreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misreport',
            name='product',
            field=models.CharField(choices=[('personal_loan', 'Personal Loan'), ('business_loan', 'Business Loan'), ('home_loan', 'Home Loan'), ('car_loan', 'Car Loan'), ('education_loan', 'Education Loan'), ('overdraft', 'Overdraft')], max_length=50),
        ),
    ]
