# Generated by Django 5.2.5 on 2026-02-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_alter_misreport_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('not_interested', 'Not Interested')], default='pending', max_length=20),
        ),
    ]
