# Generated by Django 5.2.5 on 2026-02-21 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_misreport_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('position_applied', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, choices=[('sales', 'Sales'), ('marketing', 'Marketing'), ('engineering', 'Engineering'), ('hr', 'Human Resources'), ('finance', 'Finance'), ('operations', 'Operations'), ('support', 'Customer Support'), ('admin', 'Administration')], max_length=100)),
                ('experience', models.CharField(choices=[('fresher', 'Fresher'), ('0-1', '0-1 Year'), ('1-3', '1-3 Years'), ('3-5', '3-5 Years'), ('5-10', '5-10 Years'), ('10+', '10+ Years')], default='fresher', max_length=10)),
                ('current_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notice_period', models.IntegerField(blank=True, help_text='Notice period in days', null=True)),
                ('skills', models.TextField(help_text='Comma separated skills')),
                ('qualification', models.CharField(max_length=200)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('year_of_passing', models.IntegerField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='candidates/resumes/')),
                ('portfolio_link', models.URLField(blank=True)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20)),
                ('source', models.CharField(blank=True, help_text='Source of candidate (e.g., LinkedIn, Referral, Website)', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('phone', 'Phone Interview'), ('video', 'Video Interview'), ('onsite', 'On-site Interview'), ('technical', 'Technical Interview'), ('hr', 'HR Interview'), ('final', 'Final Interview')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_date', models.DateTimeField()),
                ('duration', models.IntegerField(default=60, help_text='Duration in minutes')),
                ('location', models.CharField(help_text='Meeting link or office location', max_length=200)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from 1-5', null=True)),
                ('recommendation', models.CharField(blank=True, choices=[('hire', 'Hire'), ('consider', 'Consider'), ('reject', 'Reject')], max_length=20)),
                ('interview_link', models.URLField(blank=True, help_text='Video call link for online interviews')),
                ('reminder_sent', models.BooleanField(default=False, help_text='Whether reminder has been sent')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='accounts.candidate')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interviews', to=settings.AUTH_USER_MODEL)),
                ('interviewers', models.ManyToManyField(blank=True, related_name='interviews_conducted', to='accounts.employee')),
                ('primary_interviewer', models.ForeignKey(help_text='Main interviewer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_interviews', to='accounts.employee')),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='InterviewReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('24h', '24 Hours Before'), ('2h', '2 Hours Before'), ('30m', '30 Minutes Before')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='accounts.interview')),
                ('sent_to', models.ManyToManyField(related_name='received_reminders', to='accounts.employee')),
            ],
            options={
                'verbose_name': 'Interview Reminder',
                'verbose_name_plural': 'Interview Reminders',
            },
        ),
    ]
