# Generated by Django 5.2.5 on 2026-02-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_daily_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyNote',
        ),
    ]
