# Generated by Django 4.2.12 on 2026-02-27 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0047_delete_dailynote'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeolocationLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('user_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('distance_from_office', models.FloatField(blank=True, help_text='Distance in meters from office', null=True)),
                ('attempt_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_blocked', 'Login Blocked'), ('location_invalid', 'Invalid Location'), ('coordinates_missing', 'Missing Coordinates'), ('permission_denied', 'Permission Denied')], max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('bypass_allowed', models.BooleanField(default=False, help_text='Whether user can bypass geolocation')),
                ('user_role', models.CharField(blank=True, choices=[('employee', 'Employee'), ('team_leader', 'Team Leader'), ('manager', 'Manager'), ('hr', 'HR'), ('admin', 'Admin'), ('superadmin', 'SuperAdmin')], max_length=20, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('browser_info', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('blocked_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geolocation_attempts', to='accounts.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geolocation_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Geolocation Login Attempt',
                'verbose_name_plural': 'Geolocation Login Attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='accounts_ge_created_09dbf3_idx'), models.Index(fields=['user'], name='accounts_ge_user_id_88d4e6_idx'), models.Index(fields=['attempt_type'], name='accounts_ge_attempt_81b5be_idx'), models.Index(fields=['success'], name='accounts_ge_success_c6204b_idx')],
            },
        ),
    ]
