# Generated by Django 4.2.12 on 2026-02-21 10:08

import apps.hr_interview.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('highest_qualification', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('experience_years', models.IntegerField()),
                ('current_company', models.CharField(blank=True, max_length=100)),
                ('current_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notice_period', models.CharField(max_length=50)),
                ('applying_for_position', models.CharField(max_length=100)),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('interview_mode', models.CharField(choices=[('walk_in', 'Walk-in'), ('phone', 'Phone'), ('video', 'Video'), ('office', 'Office')], max_length=20)),
                ('interview_round', models.CharField(choices=[('hr', 'HR Round'), ('technical', 'Technical Round'), ('final', 'Final Round')], max_length=20)),
                ('interview_feedback', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('interview_done', 'Interview Done'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('on_hold', 'On Hold'), ('future_followup', 'Future Follow-up'), ('not_attended', 'Not Attended')], default='scheduled', max_length=20)),
                ('resume', models.FileField(help_text='Upload resume in PDF, DOC, or DOCX format', upload_to=apps.hr_interview.models.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates_created', to=settings.AUTH_USER_MODEL)),
                ('interview_taken_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_taken', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('interview_scheduled', 'Interview Scheduled'), ('status_changed', 'Status Changed'), ('feedback_added', 'Feedback Added'), ('interview_completed', 'Interview Completed'), ('selected', 'Selected'), ('rejected', 'Rejected')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='hr_interview.candidate')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidate Timeline',
                'verbose_name_plural': 'Candidate Timeline',
                'ordering': ['-created_at'],
            },
        ),
    ]
