# Generated by Django 4.2.12 on 2026-01-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetsIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('loan', 'Loan Form'), ('quote', 'Quote Form')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('script_url', models.URLField(help_text='Google Sheets Web App URL')),
                ('webhook_url', models.URLField(blank=True, help_text='Local webhook endpoint')),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('total_records', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Sheets Integration',
                'verbose_name_plural': 'Google Sheets Integrations',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='google_sheet_url',
            field=models.URLField(blank=True, help_text='Google Sheets Web App URL'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('loan', 'Loan Application'), ('quote', 'Quote Request'), ('general', 'General Inquiry')], default='general', max_length=20),
        ),
    ]
