# Generated by Django 4.2.12 on 2026-01-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_googlesheetsintegration_lead_google_sheet_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=False),
        ),
    ]
