# Generated by Django 4.2.12 on 2026-02-02 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0003_lead_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='csv_upload_id',
            field=models.CharField(blank=True, help_text='CSV Upload batch ID', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original uploaded filename', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='upload_batch_id',
            field=models.UUIDField(blank=True, help_text='Batch ID for uploaded leads', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='uploaded_from_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CSVUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel')], max_length=10)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('successful_imports', models.IntegerField(default=0)),
                ('failed_imports', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('uploaded_file', models.FileField(upload_to='csv_uploads/')),
                ('error_log', models.TextField(blank=True, help_text='Detailed error log')),
                ('processing_log', models.TextField(blank=True, help_text='Processing details')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('started_processing_at', models.DateTimeField(blank=True, null=True)),
                ('completed_processing_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CSV Upload Batch',
                'verbose_name_plural': 'CSV Upload Batches',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CSVFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_field', models.CharField(help_text='Original field name from CSV', max_length=255)),
                ('mapped_field', models.CharField(help_text='Mapped field in Lead model', max_length=100)),
                ('field_type', models.CharField(help_text='Field type for validation', max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('sample_value', models.TextField(blank=True, help_text='Sample value from first row')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='crm.csvuploadbatch')),
            ],
            options={
                'verbose_name': 'CSV Field Mapping',
                'verbose_name_plural': 'CSV Field Mappings',
            },
        ),
    ]
