# Generated by Django 4.2.12 on 2026-02-03 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_add_csv_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvuploadbatch',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='csv_upload_id',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='original_filename',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='upload_batch_id',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='uploaded_from_file',
        ),
        migrations.DeleteModel(
            name='CSVFieldMapping',
        ),
        migrations.DeleteModel(
            name='CSVUploadBatch',
        ),
    ]
