# Generated by Django 4.2.12 on 2026-02-11 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0019_remove_attendancebreak_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_late_days_per_month', models.PositiveIntegerField(default=3, help_text='Maximum allowed late days per month')),
                ('max_early_checkout_per_month', models.PositiveIntegerField(default=2, help_text='Maximum allowed early checkouts per month')),
                ('max_break_violations_per_month', models.PositiveIntegerField(default=5, help_text='Maximum allowed break violations per month')),
                ('auto_mark_absent_time', models.TimeField(default='12:00:00', help_text='Auto mark absent if no check-in by this time')),
                ('half_day_threshold_time', models.TimeField(default='13:00:00', help_text='After this time, considered half day')),
                ('overtime_start_time', models.TimeField(default='18:30:00', help_text='Overtime starts after this time')),
                ('overtime_approval_required', models.BooleanField(default=True, help_text='Whether overtime requires approval')),
                ('violation_notification_emails', models.TextField(blank=True, help_text='Comma-separated emails for violation notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Settings',
                'verbose_name_plural': 'Attendance Settings',
            },
        ),
        migrations.CreateModel(
            name='ShiftConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_time', models.TimeField(help_text='Shift start time')),
                ('end_time', models.TimeField(help_text='Shift end time')),
                ('late_threshold_minutes', models.PositiveIntegerField(default=15, help_text='Minutes after start time considered late')),
                ('half_day_threshold', models.TimeField(default='13:00:00', help_text='After this time, considered half day')),
                ('auto_absent_time', models.TimeField(default='12:00:00', help_text='Auto mark absent if no check-in by this time')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shift Configuration',
                'verbose_name_plural': 'Shift Configurations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Attendance date')),
                ('check_in_time', models.DateTimeField(blank=True, help_text='When employee checked in', null=True)),
                ('check_out_time', models.DateTimeField(blank=True, help_text='When employee checked out', null=True)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, help_text='Total hours worked including breaks', max_digits=5)),
                ('productive_hours', models.DecimalField(decimal_places=2, default=0, help_text='Productive hours excluding breaks', max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, help_text='Overtime hours worked', max_digits=5)),
                ('late_minutes', models.PositiveIntegerField(default=0, help_text='Minutes late to work')),
                ('early_checkout_minutes', models.PositiveIntegerField(default=0, help_text='Minutes checked out early')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('late', 'Late'), ('early_checkout', 'Early Checkout'), ('overtime', 'Overtime')], default='present', max_length=20)),
                ('violation_count', models.PositiveIntegerField(default=0, help_text='Total violations for this day')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about attendance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.employee')),
                ('shift', models.ForeignKey(blank=True, help_text='Shift configuration for this day', null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.shiftconfiguration')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BreakViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('late_login', 'Late Login'), ('extended_break', 'Extended Break'), ('early_logout', 'Early Logout'), ('inactivity', 'Inactivity During Work'), ('unauthorized_break', 'Unauthorized Break')], max_length=20)),
                ('allowed_time', models.DateTimeField(help_text='Allowed time for this activity')),
                ('actual_time', models.DateTimeField(help_text='Actual time recorded')),
                ('difference_minutes', models.PositiveIntegerField(help_text='Difference in minutes')),
                ('description', models.TextField(blank=True, help_text='Description of the violation')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_violations', to='attendance.attendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_violations', to='accounts.employee')),
            ],
            options={
                'verbose_name': 'Break Violation',
                'verbose_name_plural': 'Break Violations',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['employee', 'timestamp'], name='attendance__employe_deb7b8_idx'), models.Index(fields=['attendance', 'violation_type'], name='attendance__attenda_0b35f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='BreakConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField(help_text='Break start time')),
                ('end_time', models.TimeField(help_text='Break end time')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Break duration in minutes')),
                ('is_paid', models.BooleanField(default=True, help_text='Whether this break is paid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='attendance.shiftconfiguration')),
            ],
            options={
                'verbose_name': 'Break Configuration',
                'verbose_name_plural': 'Break Configurations',
                'ordering': ['start_time'],
                'unique_together': {('shift', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'date'], name='attendance__employe_08d913_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'status'], name='attendance__date_3889e6_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['check_in_time'], name='attendance__check_i_377917_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
